version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: ecom-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecomdb
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  app:
    build: .
    container_name: ecom-app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecomdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ecomuser
      SPRING_DATASOURCE_PASSWORD: secretpassword
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
