version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Snsiva@5
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"    # publish port so host (127.0.0.1) can reach it
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
